language: php

script: php ./parse-counters.php

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git checkout master
- git add *.csv
- git status
- 'git commit --message "Updated data files"'
- git push
